### ISSUE TITLE
Keep aspect ratio

### ISSUE THREAD

**Issue by mat1jaczyyy** [tma02/twitch-emote-resizer#7]
Some images get really distorted. A checkbox which keeps the original aspect ratio of the image and fills the rest with transparent would be nice.

Example png for repro
![strum note](https://user-images.githubusercontent.com/13300194/125539969-10f652e6-7cd3-45d2-ac46-e34bd946c121.png)

**Comment by tma02** [comment]
I went ahead and made this the default behavior, I figure there's not much reason someone would want to stretch their source image into a square.

**Comment by mat1jaczyyy** [comment]
Thank you! On a secondary note, I'm not sure you should keep the build folder in the repo? I think it should be gitignored...?

**Comment by tma02** [comment]
> Thank you! On a secondary note, I'm not sure you should keep the build folder in the repo? I think it should be gitignored...?

The build path is not in the gitignore so that its subtree can be pushed to the gh-pages branch. It's possible to temporarily remove the build path from the gitignore before pushing the subtree, but I don't think a project like this warrants any custom push procedures. You're certainly welcome to open a new issue regarding this.
